version: '2.2'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
    volumes:
      - data01:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node      
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1   
    networks:
      - articles-net
       

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    networks:
      - articles-net 
    ports:
      - 5435:5432     

  articles:
    build:
      context: .
      dockerfile: Dockerfile
    image: articles:latest
    ports:
      - 3001:3001
    env_file: .env
    environment:
      RAILS_ENV: development   
    networks:
      - articles-net       
    depends_on:
      - db
      - elastic
    command: ['rails', 'server', '-b', '0.0.0.0', '-p', '3001']

volumes:
  data01:

networks:
  articles-net:
    driver: bridge
